### ISSUE TITLE
Pre-trained ANN

### ISSUE THREAD

**Issue by lucasvictorsp** [nikonkate/DQBirds#1]
Hello,

I'm trying to do some tests with Angry Birds boots.
I downloaded the project and I could to execute it following the instructions given (the 5 steps in README.md), but initially there is no pre-trained ANN that was saved in the project (in ./ddqn_offline_model/), so the network launches the birds in a pseudo-random way?

Is my reasoning correct? Is ANN trained within the AIBirds competition's famework?

Thank you for your help.

**Comment by nikonkate** [comment]
Hi,

You are correct, the pre-trained model that I was using on competition is missing as it is quite big. However, the code should allow you to train your own model from the scratch. It is rather random at the beginning since it takes some time for the agent to learn the correct policy. The only thing you will need to change in order to train the model in the same way as I did, is to change some of the model hyper parameters defined in the global constants.

The agent was adopted for the AIBirds competition framework and Chrome version of the game, so the agent consists of the two parts Java agent that executes the actions, interacts with the game and stores the experience and Python agent that learns to play that game and decides what action to take.

Hope that helps!

**Comment by lucasvictorsp** [comment]
I got it.

Thank for your help.
